/* Bustan species catalogue - tuned for a Levant / Mediterranean garden.

   sow: months (1-12) when this can go in the ground. Two pushes, autumn and
   spring, with summer nearly empty - that is the climate, not an omission.
   kc:  FAO-56 crop coefficient family, used by the watering engine.
   w:   "et" runs the evapotranspiration balance, "dry" the dry-down branch. */
(function (root) {
  function S(id, en, ar, group, arch, sow, germ, days, kc, sun, w, pal, tips) {
    return { id: id, en: en, ar: ar, group: group, arch: arch, sow: sow,
             germ: germ, days: days, kc: kc, sun: sun, w: w, art: pal, tips: tips };
  }
  var AUT = [9, 10, 11], AUTW = [9, 10, 11, 12], WIN = [10, 11, 12, 1], SPR = [3, 4, 5],
      SPR2 = [2, 3, 4], HOT = [4, 5, 6], COOL = [9, 10, 11, 12, 1, 2], ANY = [1,2,3,4,5,6,7,8,9,10,11,12];

  var LIST = [
  /* ---- herbs ---- */
  S("basil","Basil","حبق","herb","bush",[3,4,5,6],7,60,"herb","full","et",
    {leaf:"#4e9a4a",dark:"#2f6b38",light:"#7fc26a",accent:"#e8e0f0",stem:"#3f7a3a"},
    ["Pinch the growing tip every couple of weeks - it doubles the bush and delays flowering.","Flowers mean the leaves turn bitter. Pick them off unless you want seed.","Dies at the first cold night. Take cuttings in September to carry it through."]),
  S("mint","Mint","نعناع","herb","bush",[2,3,4,9,10],10,60,"herb","part","et",
    {leaf:"#4aa06a",dark:"#2f7048",light:"#86cea0",accent:"#d8d0e8",stem:"#3f8a58"},
    ["Grow it in its own pot. In a bed it will take the bed.","Cut it hard - it comes back thicker every time.","Happier in afternoon shade here than in full sun."]),
  S("parsley","Parsley","بقدونس","herb","bush",[9,10,11,2,3],21,80,"herb","part","et",
    {leaf:"#3f8a45",dark:"#28602f",light:"#6fbe5e",accent:null,stem:"#357a3a"},
    ["Slow to germinate - three weeks is normal, not failure.","Soak the seed overnight first.","Cut outer stems at the base; the centre keeps producing."]),
  S("coriander","Coriander","كزبرة","herb","bush",[9,10,11,2,3],10,45,"herb","part","et",
    {leaf:"#6fae5a",dark:"#48803c",light:"#9ed17f",accent:"#f0ece0",stem:"#5a9a4a"},
    ["Bolts the moment it gets hot. Autumn sowing gives far more leaf.","Sow a short row every three weeks instead of one long one.","Let the last sowing flower and you get coriander seed."]),
  S("thyme","Thyme","زعتر","herb","needle",[10,11,3,4],14,90,"herb","full","dry",
    {leaf:"#7a8a5a",dark:"#4f5f3a",light:"#a8b487",accent:"#d6a8c0",stem:"#6a7a4a"},
    ["Wants poor, sharply drained soil. Rich compost makes it floppy and weak.","Never let it sit wet in winter - that is what kills it, not cold.","Trim after flowering to stop it going woody in the middle."]),
  S("sage","Sage","ميرمية","herb","bush",[10,11,3],21,90,"herb","full","dry",
    {leaf:"#8fa08a",dark:"#5f7060",light:"#b8c4b0",accent:"#b0a8d0",stem:"#7a8a76"},
    ["Drought-tolerant once rooted. Overwatering is the usual cause of death.","Cut back by a third in spring to keep it compact.","Leaves are strongest just before it flowers."]),
  S("oregano","Oregano","زعتر بري","herb","bush",[10,11,3,4],14,90,"herb","full","dry",
    {leaf:"#6a8a4a",dark:"#455f30",light:"#9ab876",accent:"#e0d0e8",stem:"#5a7a40"},
    ["Flavour concentrates in poor soil and full sun.","Divide the clump every third year.","Dries beautifully - hang a bunch upside down out of the sun."]),
  S("rosemary","Rosemary","إكليل الجبل","herb","needle",[10,11,3,4],28,180,"herb","full","dry",
    {leaf:"#5a7a5a",dark:"#38553f",light:"#8aa88a",accent:"#8fa8d6",stem:"#4a6a4a"},
    ["Strikes far more reliably from a cutting than from seed.","Established plants want almost no summer water.","Will not forgive a waterlogged pot. Grit in the mix."]),
  S("dill","Dill","شبت","herb","needle",[9,10,11,2,3],10,60,"herb","full","et",
    {leaf:"#8fbe7a",dark:"#5f8a50",light:"#b8d8a4",accent:"#e8d87a",stem:"#7aa868"},
    ["Sow where it is to grow - it hates being moved.","Goes to seed fast in heat. Autumn is its season here.","Do not plant next to coriander; they cross."]),
  S("chives","Chives","ثوم معمر","herb","bulb",[9,10,11,2,3],14,80,"herb","part","et",
    {leaf:"#4a9a5a",dark:"#2f7040",light:"#7fc48a",accent:"#b87ac0",stem:"#3f8a4a"},
    ["Cut from the outside, two centimetres above soil.","The purple flowers are edible and good in salad.","Split the clump every couple of years or it thins out."]),
  S("lemonbalm","Lemon balm","مليسة","herb","bush",[9,10,3],14,70,"herb","part","et",
    {leaf:"#7fbe5a",dark:"#548a3a",light:"#a8d888",accent:"#f0ecd0",stem:"#6aa84a"},
    ["Spreads by root like mint. Pot it.","Afternoon shade keeps the leaves from scorching.","Cut it back hard mid-season for fresh growth."]),

  /* ---- winter vegetables ---- */
  S("lettuce","Lettuce","خس","winter","rosette",COOL,7,55,"leafy","part","et",
    {leaf:"#7fc257",dark:"#4f8a38",light:"#a8dc7c",accent:"#c9e89a",stem:"#6aa84a"},
    ["Pick outer leaves and it keeps going for months.","Bolts and turns bitter above about 25 degrees.","Sow a few every fortnight rather than all at once."]),
  S("spinach","Spinach","سبانخ","winter","rosette",[10,11,12,1],10,45,"leafy","part","et",
    {leaf:"#2f6b38",dark:"#1c4a26",light:"#548a4a",accent:null,stem:"#28602f"},
    ["Truly a cold-season crop - it bolts the moment spring warms.","Germinates poorly in warm soil. Wait for the first rains.","Cut leaves young; older ones go tough."]),
  S("chard","Swiss chard","سلق","winter","strap",[9,10,11,2],10,60,"leafy","full","et",
    {leaf:"#3f7a45",dark:"#28582e",light:"#6aa85a",accent:"#d6455f",stem:"#d6455f"},
    ["The most forgiving green you can grow here. Survives real neglect.","Cut outer stems at the base and it produces for months.","Handles more heat than spinach - it will run through spring."]),
  S("cabbage","Cabbage","ملفوف","winter","rosette",[8,9,10],10,90,"leafy","full","et",
    {leaf:"#6f9e6a",dark:"#456d42",light:"#9ec49a",accent:"#b8d0b0",stem:"#5a8a56"},
    ["Needs steady water or the head splits.","Watch for cabbage white caterpillars from the first warm week.","Firm the soil around the stem; loose roots mean loose heads."]),
  S("cauliflower","Cauliflower","قرنبيط","winter","rosette",[8,9],10,100,"leafy","full","et",
    {leaf:"#7a9e72",dark:"#4f6d48",light:"#a4c49c",accent:"#f0ead6",stem:"#6a8a62"},
    ["Fold outer leaves over the curd to keep it white.","Fussier than cabbage about steady moisture.","A check in growth gives you a tiny head - keep it moving."]),
  S("broccoli","Broccoli","بروكلي","winter","rosette",[8,9,10],10,85,"leafy","full","et",
    {leaf:"#5a8a52",dark:"#3a5f34",light:"#87b47c",accent:"#3a6b3a",stem:"#4f7a48"},
    ["Cut the main head and side shoots keep coming for weeks.","Harvest while the beads are tight; yellow means you waited too long."]),
  S("radish","Radish","فجل","winter","root",[9,10,11,12,1,2,3],5,28,"root","full","et",
    {leaf:"#6fae5a",dark:"#48803c",light:"#9ed17f",accent:"#d6455f",stem:"#5a9a4a"},
    ["Fastest thing in the garden - four weeks from seed.","Thin them or you get leaves and no root.","Hot weather makes them woody and sharp."]),
  S("carrot","Carrot","جزر","winter","root",[9,10,11,12,2],14,90,"root","full","et",
    {leaf:"#6aae5a",dark:"#44803a",light:"#9ad17c",accent:"#e07a20",stem:"#5a9a4a"},
    ["Wants loose, stone-free soil or the roots fork.","Keep the surface damp until they germinate - that is the hard part.","Thin to a finger's width apart. Crowded carrots stay small."]),
  S("beet","Beetroot","شمندر","winter","root",[9,10,11,2],10,80,"root","full","et",
    {leaf:"#5a8a48",dark:"#3a5f2f",light:"#8ab472",accent:"#8f2f4f",stem:"#8f2f4f"},
    ["Each seed is a cluster - expect several seedlings and thin them.","The leaves are as good as the root. Do not throw them out."]),
  S("turnip","Turnip","لفت","winter","root",AUT,7,55,"root","full","et",
    {leaf:"#7ab45a",dark:"#4f8038",light:"#a4d67f",accent:"#e8e0d0",stem:"#6aa84a"},
    ["Best picked small - golf-ball size is sweeter than fist size."]),
  S("fava","Broad bean","فول","winter","climber",[10,11,12],10,120,"fruit","full","et",
    {leaf:"#7a9e5a",dark:"#4f6d38",light:"#a4c47f",accent:"#8fae5a",stem:"#6a8a4a"},
    ["The classic Levant winter crop. Sows itself into the first rains.","Pinch the top out once pods set - it stops blackfly.","Leave the roots in the ground; they feed whatever follows."]),
  S("peas","Peas","بازلاء","winter","climber",[10,11,12],10,90,"fruit","full","et",
    {leaf:"#7fbe5e",dark:"#548a3a",light:"#a8d888",accent:"#8fce6a",stem:"#6aa84a"},
    ["Give them something to climb from day one.","Pick constantly - a pod left to swell stops the plant."]),
  S("garlic","Garlic","ثوم","winter","bulb",[10,11],14,240,"root","full","et",
    {leaf:"#6aae6a",dark:"#44804a",light:"#9ad18f",accent:"#eae2d2",stem:"#5a9a5a"},
    ["Plant cloves pointy end up, in autumn. It needs the cold to split.","Stop watering once the lower leaves yellow.","Shop garlic often carries disease - buy seed garlic once, then save your own."]),
  S("onion","Onion","بصل","winter","bulb",[10,11,12],14,150,"root","full","et",
    {leaf:"#6fae7a",dark:"#48805a",light:"#9ed19a",accent:"#c9a06a",stem:"#5a9a68"},
    ["Sets are far easier than seed for a first try.","Stop watering when the tops flop - that is it telling you it is done."]),
  S("leek","Leek","كراث","winter","bulb",[8,9,10],14,150,"root","full","et",
    {leaf:"#5a9a6a",dark:"#3a704a",light:"#8ac490",accent:"#dfe8d0",stem:"#4f8a5a"},
    ["Earth up around the stem as it grows for a long white shank.","Slow, but it sits in the ground all winter without complaint."]),

  /* ---- summer vegetables ---- */
  S("tomato","Tomato","بندورة","summer","fruitvine",SPR2,8,110,"fruit","full","et",
    {leaf:"#4a8a3f",dark:"#2e5c2a",light:"#7fc26a",accent:"#d63b2f",stem:"#3f7a35",fruitR:2},
    ["Transplant deep - buried stem grows extra roots.","Water at the base, never the leaves, and water evenly. Uneven watering splits fruit and causes blossom end rot.","Pinch side shoots on vine types; leave bush types alone.","Give it a stake on day one, not when it flops."]),
  S("pepper","Sweet pepper","فلفل حلو","summer","fruitvine",SPR2,12,110,"fruit","full","et",
    {leaf:"#458a45",dark:"#2a5c2e",light:"#78c26a",accent:"#e8a020",stem:"#3a7a3a",fruitR:2},
    ["Needs real warmth to set fruit - do not rush it outside.","Leaves scorch above 38 degrees. Light shade cloth in July helps."]),
  S("chili","Chilli","فلفل حار","summer","fruitvine",SPR2,12,100,"fruit","full","et",
    {leaf:"#3f7a3a",dark:"#265226",light:"#6fb45a",accent:"#cc2020",stem:"#357035",fruitR:1},
    ["Heat in the fruit rises when you water it a little less.","Picks and dries well - a good crop for a small pot."]),
  S("eggplant","Aubergine","باذنجان","summer","fruitvine",SPR2,10,120,"fruit","full","et",
    {leaf:"#4a7a45",dark:"#2e5230",light:"#7aae6a",accent:"#6b3d8f",stem:"#3f6a3a",fruitR:2},
    ["Loves the heat - one of the few things that enjoys a Levant July.","Watch for red spider mite in dry heat; spray the undersides.","Pick young and glossy. Dull skin means it is past it."]),
  S("cucumber","Cucumber","خيار","summer","cucurbit",[3,4,5,8],7,60,"fruit","full","et",
    {leaf:"#4f9a45",dark:"#316b2c",light:"#82c86f",accent:"#4f9e3a",stem:"#44803a",fruitR:2},
    ["Thirsty. Uneven water makes bitter fruit.","Grow it up a net - straighter fruit, less mildew.","Pick every day once it starts. They swell overnight."]),
  S("squash","Courgette","كوسا","summer","cucurbit",[3,4,5,8],7,55,"fruit","full","et",
    {leaf:"#5a9a48",dark:"#3a6b2f",light:"#8ac872",accent:"#8fbf3a",stem:"#4f8a3f",fruitR:2},
    ["One plant feeds a household. Two is a mistake you make once.","Pick at finger length - flavour and texture are best small.","Powdery mildew late in the season is normal; water the soil, not the leaves."]),
  S("okra","Okra","بامية","summer","cane",HOT,10,60,"fruit","full","et",
    {leaf:"#5a9a4a",dark:"#3a6b30",light:"#8ac874",accent:"#8fce5a",stem:"#4f8a40"},
    ["One of the few things that genuinely thrives in high summer here.","Pick every other day - pods go woody within a week.","Soak seed overnight; the coat is hard."]),
  S("molokhia","Molokhia","ملوخية","summer","cane",HOT,7,60,"leafy","full","et",
    {leaf:"#3f8a3a",dark:"#265c26",light:"#6fb45a",accent:null,stem:"#357a32"},
    ["Sow when the soil is properly warm - it sulks in cool ground.","Cut the top and it branches out for a second picking.","Handles heat that flattens everything else."]),
  S("beans","Green beans","فاصولياء","summer","climber",[3,4,5,8,9],8,60,"fruit","full","et",
    {leaf:"#4f9a4a",dark:"#316b30",light:"#82c874",accent:"#7fbe5e",stem:"#44803f"},
    ["Do not soak the seed - it rots. Sow into damp soil.","Pick constantly to keep it producing."]),
  S("cowpea","Black-eyed pea","لوبياء","summer","climber",HOT,8,70,"fruit","full","et",
    {leaf:"#5a9a52",dark:"#3a6b36",light:"#8ac87c",accent:"#d8d0b0",stem:"#4f8a48"},
    ["Handles heat and poor soil better than common beans.","Fixes nitrogen - a good thing to follow with a leafy crop."]),
  S("watermelon","Watermelon","بطيخ","summer","cucurbit",[3,4],8,100,"fruit","full","et",
    {leaf:"#4a8a42",dark:"#2e5c2c",light:"#7ac26a",accent:"#2e7a3a",stem:"#3f7a38",fruitR:3},
    ["Needs room - two square metres per plant is not excessive.","Cut water back as the fruit ripens for sweeter flesh.","Ready when the curly tendril nearest the fruit dries brown."]),
  S("melon","Melon","شمام","summer","cucurbit",[3,4],8,95,"fruit","full","et",
    {leaf:"#54924a",dark:"#356632",light:"#84c672",accent:"#d9c07a",stem:"#498238",fruitR:2},
    ["Ripe when it smells like melon at the stem end and slips off easily."]),
  S("sweetpotato","Sweet potato","بطاطا حلوة","summer","trailing",[4,5],14,120,"root","full","et",
    {leaf:"#5a9a5a",dark:"#3a6b3a",light:"#8ac88a",accent:"#c9705a",stem:"#4f8a4a"},
    ["Grown from slips, not seed. Root a shoot in water first.","Drought-tolerant once away. Almost the ideal Levant summer crop."]),
  S("corn","Sweetcorn","ذرة","summer","cane",SPR,8,90,"fruit","full","et",
    {leaf:"#5a9a45",dark:"#3a6b2e",light:"#8ac870",accent:"#e8c35a",stem:"#4f8a3c"},
    ["Plant in a block, not a row - it is wind-pollinated and a single row sets badly.","Hungry and thirsty. Not a crop for a small pot."]),

  /* ---- ornamental and succulent ---- */
  S("queenofnight","Queen of the Night","ملكة الليل","orn","pad",SPR,21,1095,"succulent","part","dry",
    {leaf:"#3f7a45",dark:"#28582e",light:"#6aa858",accent:"#d98aa8",accent2:"#e8c35a",light2:"#f2e9d6",stem:"#357a3a"},
    ["Blooms one night a year, after dark, and is finished by dawn.","Give it a cool dry rest from November to February - that is what induces the bloom.","Bright indirect light. Direct summer sun scorches the pads.","Likes being slightly pot-bound. Do not repot when buds are forming.","From a visible bud, expect 18 to 25 days to opening."]),
  S("jasmine","Jasmine","ياسمين","orn","flower",[3,4,5,9,10],21,365,"herb","full","et",
    {leaf:"#2f6b38",dark:"#1c4a26",light:"#5a9a4a",accent:"#f6efdc",accent2:"#e8dcb0",stem:"#28602f"},
    ["Scent carries furthest in the evening - plant it near where you sit.","Prune right after flowering, not before, or you cut off next year's buds."]),
  S("geranium","Geranium","غرنوقي","orn","flower",[3,4,9,10],14,120,"herb","full","dry",
    {leaf:"#5a9a4a",dark:"#3a6b30",light:"#8ac874",accent:"#d6455f",accent2:"#f0d0d8",stem:"#4f8a40"},
    ["Deadhead constantly and it flowers all season.","Lets you forget to water it. Overwatering is the real risk.","Takes from cuttings almost too easily."]),
  S("bougainvillea","Bougainvillea","جهنمية","orn","flower",SPR,21,365,"herb","full","dry",
    {leaf:"#4a8a45",dark:"#2e5c2e",light:"#7ac270",accent:"#c9407a",accent2:"#e88ab0",stem:"#3f7a3a"},
    ["Flowers hardest when kept slightly dry and slightly hungry.","The colour is bracts, not petals. Full sun or you get all leaf.","Prune hard after each flush."]),
  S("aloe","Aloe vera","صبار","orn","succulent",[3,4,5,6,7,8,9],21,730,"succulent","full","dry",
    {leaf:"#6fae7a",dark:"#48805a",light:"#a8d6b0",accent:"#e8a020",stem:"#5a9a68"},
    ["Water only when the mix is dry all the way through.","Offsets around the base can be potted up as new plants.","Wants grit. Ordinary potting compost holds far too much water."]),
  S("jade","Jade plant","شجرة اليشم","orn","succulent",[3,4,5,6,7,8,9],21,730,"succulent","full","dry",
    {leaf:"#4a8a5a",dark:"#2e5c38",light:"#7fbe8a",accent:"#f0e0e8",stem:"#6b4a2c"},
    ["Wrinkled leaves mean thirsty; soft mushy leaves mean overwatered.","Almost impossible to kill by neglect. Very possible to kill by kindness."]),
  S("snake","Snake plant","لسان الحماة","orn","spike",ANY,28,730,"succulent","shade","dry",
    {leaf:"#4a7a4a",dark:"#2f5a35",light:"#c9c47a",accent:"#c9c47a",stem:"#3f6a3f"},
    ["Will live in a dark corner on almost no water.","Water once a month in winter. Genuinely.","The single most forgiving plant on this list."]),
  S("pothos","Pothos","بوتس","orn","trailing",ANY,21,365,"herb","shade","et",
    {leaf:"#5a9a4a",dark:"#3a6b30",light:"#c9d67a",accent:null,stem:"#4f8a40"},
    ["Roots from a cutting in a glass of water within a fortnight.","Yellow leaves almost always mean too much water, not too little."]),
  S("monstera","Monstera","مونستيرا","orn","trailing",[3,4,5,6,7,8,9],21,730,"herb","part","et",
    {leaf:"#2f6b38",dark:"#1c4a26",light:"#5a9a4a",accent:null,stem:"#28602f"},
    ["Splits in the leaves come with maturity and good light, not with age alone.","Wipe the leaves - dust genuinely slows it down."]),
  S("echeveria","Echeveria","إتشيفيريا","orn","succulent",[3,4,5,6,7,8,9],21,365,"succulent","full","dry",
    {leaf:"#9ab0a0",dark:"#6a8078",light:"#c9d6c4",accent:"#d98aa8",stem:"#8aa090"},
    ["The dusty bloom on the leaves is a sunscreen. Do not rub it off.","Water the soil, never into the rosette - trapped water rots the centre."]),

  /* ---- container trees ---- */
  S("lemon","Lemon tree","ليمون","tree","tree",[3,4,10,11],28,1095,"tree","full","et",
    {leaf:"#3f7a42",dark:"#28582c",light:"#6aa858",accent:"#e8c020",stem:"#6b4a2c",fruitR:2},
    ["Feed with a citrus feed through spring and summer; they are hungry.","Yellow leaves with green veins means iron - common in our limey soil.","Does well in a large pot, which also lets you shelter it from frost."]),
  S("olive","Olive","زيتون","tree","tree",[3,4,10,11],28,1460,"tree","full","dry",
    {leaf:"#6a8a6a",dark:"#455f48",light:"#9ab098",accent:"#4a3a5a",stem:"#7a6a52",fruitR:1},
    ["Wants sun, drainage and very little else.","Needs a cold spell in winter to set fruit properly.","Prune to an open centre so light reaches the middle."]),
  S("fig","Fig","تين","tree","tree",[1,2,3],28,1095,"tree","full","dry",
    {leaf:"#4a8a45",dark:"#2e5c2c",light:"#7ac26a",accent:"#6b3d5f",stem:"#8a7a62",fruitR:2},
    ["Plant while dormant in winter.","Restricting the roots gives more fruit and less leaf - a pot suits it.","Ripe when it softens and droops. Firm figs never ripen off the tree."]),
  S("pomegranate","Pomegranate","رمان","tree","tree",[1,2,3],28,1095,"tree","full","dry",
    {leaf:"#4a8a45",dark:"#2e5c2c",light:"#7ac26a",accent:"#cc3040",stem:"#7a6248",fruitR:2},
    ["Irregular watering as fruit ripens splits the skin. Keep it even.","Takes real heat and poor soil without complaint."]),
  S("grape","Grapevine","عنب","tree","climber",[1,2],28,1095,"tree","full","dry",
    {leaf:"#5a8a45",dark:"#3a5f2c",light:"#8ab470",accent:"#7a4a8f",stem:"#7a6248"},
    ["Prune hard in winter while dormant - this year's fruit comes on new wood.","A pergola is the traditional answer here, and it shades your seating too."])
  ];

  var BY_ID = {};
  for (var i = 0; i < LIST.length; i++) BY_ID[LIST[i].id] = LIST[i];

  root.SPECIES = LIST;
  root.SPECIES_BY_ID = BY_ID;
})(typeof window !== "undefined" ? window : global);
